services:
  ignition:
    build:
      context: .
      dockerfile: bootstrap/Dockerfile
    container_name: ignition-tfpr
    ports:
      - "8088:8088"
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - GATEWAY_ADMIN_PASSWORD=password123
      - GATEWAY_ADMIN_USERNAME=admin
      - IGNITION_EDITION=standard
    post_start:
      - command: /usr/local/bin/ignition/gwcmd.sh -s /restore.gwbk -y
      - command: /usr/local/bin/ignition/gwcmd.sh -r
